import Link from "next/link";
import { products } from "../../../lib/catalog";

export default function OpusPage(){
  const opus=products.filter(p=>p.brand==="Opus");
  return <><Header/><main className="page"><div className="container"><div className="brand-hero"><div><p className="eyebrow">FEATURED BRAND</p><h1>Opus Paints</h1><p className="lead">Explore selected Opus paint products available through our store. Contact us for current availability, sizes and colours.</p><a className="button primary" href="https://wa.me/919999999999" target="_blank">Ask about Opus products</a></div><div className="opus-badge large-badge">OPUS</div></div><div className="section-heading"><div><p className="eyebrow">OPUS RANGE</p><h2>Featured products</h2></div></div><div className="product-grid large">{opus.map(p=><Link key={p.slug} href={`/products/${p.slug}`} className="product-card"><div className={`product-art ${p.tone}`}><span>{p.short}</span></div><div className="product-info"><h3>{p.name}</h3><p>{p.description}</p><span className="product-link">View product →</span></div></Link>)}</div></div></main><Footer/></>;
}
function Header(){return <header className="site-header"><div className="container nav"><Link href="/" className="brand"><span className="brand-mark">CH</span><span><strong>Canacona Hardware</strong><small>& Paints</small></span></Link><nav><Link href="/products">Products</Link><Link href="/categories">Categories</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></nav><a className="nav-cta" href="https://wa.me/919999999999" target="_blank">WhatsApp</a></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><strong>Canacona Hardware & Paints</strong><p>Paints • Hardware • Tools • Accessories</p></div><div><Link href="/products">Products</Link><Link href="/contact">Contact</Link><Link href="/about">About</Link></div><div><span>Canacona, Goa</span><span>+91 99999 99999</span></div></div></footer>}
